/**
 * Worker entry point. Thin fetch handler; request routing and orchestration live in workerApp.ts.
 */

import type { Env } from "./env.js";
import { RateLimitDO } from "./rateLimitDO.js";
import { CircuitBreakerDO } from "./circuitBreakerDO.js";
import {
  handleRequest,
  handleControlPlaneRequest,
  createSupabaseClient,
  handleCreateMemory,
  handleCreateConversation,
  handleListMemories,
  handleGetMemory,
  handleDeleteMemory,
  handleSearch,
  handleFeedback,
  handleCreateEvalSet,
  handleListEvalSets,
  handleDeleteEvalSet,
  handleCreateEvalItem,
  handleListEvalItems,
  handleDeleteEvalItem,
  handleRunEvalSet,
  handleContextFeedback,
  handlePruningMetrics,
  handleExplainAnswer,
  handleContext,
  handleContextExplain,
  handleUsageToday,
  handleListAuditLog,
  handleBillingStatus,
  handleBillingCheckout,
  handleBillingPortal,
  handleBillingWebhook,
  handleMemoryWebhookIngest,
  handleReprocessDeferredWebhooks,
  handleAdminBillingHealth,
  handleFounderPhase1Metrics,
  handleCleanupExpiredSessions,
  handleMemoryHygiene,
  handleImport,
  handleCreateWorkspace,
  handleCreateApiKey,
  handleListApiKeys,
  handleRevokeApiKey,
  safeKvTtl,
  performSearch,
  performListMemories,
  deleteMemoryCascade,
  makeExportResponse,
  normalizeSearchPayload,
  normalizeMemoryListParams,
  assertBodySize,
  buildExportArtifact,
  wantsZipResponse,
  importArtifact,
  parseApiKeyMeta,
  redact,
  buildPayURequestHashInput,
  buildPayUResponseReverseHashInput,
  computeSha512Hex,
  emitAuditLog,
  parseAllowedOrigins,
  isOriginAllowed,
  makeCorsHeaders,
  chunkText,
  chunkTextWithProfile,
  dedupeFusionResults,
  finalizeResults,
} from "./workerApp.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return handleRequest(request, env);
  },
  RateLimitDO,
  CircuitBreakerDO,
};

export { RateLimitDO, CircuitBreakerDO, createSupabaseClient, handleControlPlaneRequest };
export {
  handleCreateMemory,
  handleCreateConversation,
  handleListMemories,
  handleGetMemory,
  handleDeleteMemory,
  handleSearch,
  handleFeedback,
  handleCreateEvalSet,
  handleListEvalSets,
  handleDeleteEvalSet,
  handleCreateEvalItem,
  handleListEvalItems,
  handleDeleteEvalItem,
  handleRunEvalSet,
  handleContextFeedback,
  handlePruningMetrics,
  handleExplainAnswer,
  handleContext,
  handleContextExplain,
  handleUsageToday,
  handleListAuditLog,
  handleBillingStatus,
  handleBillingCheckout,
  handleBillingPortal,
  handleBillingWebhook,
  handleMemoryWebhookIngest,
  handleReprocessDeferredWebhooks,
  handleAdminBillingHealth,
  handleFounderPhase1Metrics,
  handleCleanupExpiredSessions,
  handleMemoryHygiene,
  handleImport,
  handleCreateWorkspace,
  handleCreateApiKey,
  handleListApiKeys,
  handleRevokeApiKey,
  safeKvTtl,
  performSearch,
  performListMemories,
  deleteMemoryCascade,
  makeExportResponse,
  normalizeSearchPayload,
  normalizeMemoryListParams,
  assertBodySize,
  buildExportArtifact,
  wantsZipResponse,
  importArtifact,
  parseApiKeyMeta,
  redact,
  buildPayURequestHashInput,
  buildPayUResponseReverseHashInput,
  computeSha512Hex,
  emitAuditLog,
  parseAllowedOrigins,
  isOriginAllowed,
  makeCorsHeaders,
  chunkText,
  chunkTextWithProfile,
  dedupeFusionResults,
  finalizeResults,
};
