/**
 * Worker entry point. Thin fetch handler; all logic lives in workerApp.ts (Phase 2: Worker modularization).
 */

import type { Env } from "./env.js";
import { RateLimitDO } from "./rateLimitDO.js";
import { CircuitBreakerDO } from "./circuitBreakerDO.js";
import {
  handleRequest,
  createSupabaseClient,
  handleCreateMemory,
  handleListMemories,
  handleGetMemory,
  handleDeleteMemory,
  handleSearch,
  handleContext,
  handleUsageToday,
  handleCreateEpisode,
  handleListEpisodes,
  handleBillingStatus,
  handleBillingCheckout,
  handleBillingPortal,
  handleBillingWebhook,
  handleReprocessDeferredWebhooks,
  handleAdminBillingHealth,
  handleCleanupExpiredSessions,
  handleMemoryHygiene,
  handleExport,
  handleImport,
  handleRunEval,
  handleCreateWorkspace,
  handleCreateApiKey,
  handleListApiKeys,
  handleRevokeApiKey,
  safeKvTtl,
  performSearch,
  performListMemories,
  deleteMemoryCascade,
  makeExportResponse,
  normalizeSearchPayload,
  normalizeMemoryListParams,
  assertBodySize,
  buildExportArtifact,
  wantsZipResponse,
  importArtifact,
  parseApiKeyMeta,
  redact,
  buildPayURequestHashInput,
  buildPayUResponseReverseHashInput,
  computeSha512Hex,
  emitAuditLog,
  parseAllowedOrigins,
  isOriginAllowed,
  makeCorsHeaders,
  chunkText,
  dedupeFusionResults,
  finalizeResults,
} from "./workerApp.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return handleRequest(request, env);
  },
  RateLimitDO,
  CircuitBreakerDO,
};

export { RateLimitDO, CircuitBreakerDO, createSupabaseClient };
export {
  handleCreateMemory,
  handleListMemories,
  handleGetMemory,
  handleDeleteMemory,
  handleSearch,
  handleContext,
  handleUsageToday,
  handleCreateEpisode,
  handleListEpisodes,
  handleBillingStatus,
  handleBillingCheckout,
  handleBillingPortal,
  handleBillingWebhook,
  handleReprocessDeferredWebhooks,
  handleAdminBillingHealth,
  handleCleanupExpiredSessions,
  handleMemoryHygiene,
  handleExport,
  handleImport,
  handleRunEval,
  handleCreateWorkspace,
  handleCreateApiKey,
  handleListApiKeys,
  handleRevokeApiKey,
  safeKvTtl,
  performSearch,
  performListMemories,
  deleteMemoryCascade,
  makeExportResponse,
  normalizeSearchPayload,
  normalizeMemoryListParams,
  assertBodySize,
  buildExportArtifact,
  wantsZipResponse,
  importArtifact,
  parseApiKeyMeta,
  redact,
  buildPayURequestHashInput,
  buildPayUResponseReverseHashInput,
  computeSha512Hex,
  emitAuditLog,
  parseAllowedOrigins,
  isOriginAllowed,
  makeCorsHeaders,
  chunkText,
  dedupeFusionResults,
  finalizeResults,
};
